export const FETCH_GAMES_REQUEST = 'FETCH_GAMES_REQUEST';
export const FETCH_GAMES_SUCCESS = 'FETCH_GAMES_SUCCESS';
export const FETCH_GAMES_FAILURE = 'FETCH_GAMES_FAILURE';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_PLATFORM_FILTER = 'SET_PLATFORM_FILTER';
export const SET_SELECTED_GENRES = 'SET_SELECTED_GENRES';
export const SET_SORT_TYPE = 'SET_SORT_TYPE';
export const SET_SORT_ORDER = 'SET_SORT_ORDER';
export const SET_UNIQUE_GENRES = 'SET_UNIQUE_GENRES';

export const TOGGLE_FIRST_TOUR = 'TOGGLE_FIRST_TOUR';
export const TOGGLE_SECOND_TOUR = 'TOGGLE_SECOND_TOUR';